{"cells":[{"cell_type":"markdown","metadata":{"colab_type":"text","id":"SvphuJLD141j"},"outputs":[],"source":["# Website\n","### https://www.hksuning.com/\n","\n","***"]},{"cell_type":"markdown","metadata":{"colab_type":"text","id":"hRy3Kw2bO0ns"},"outputs":[],"source":["# Installation\n","### If you are running this notebook for the first time, please the follow one sell, otherwise, please ignore."]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{},"colab_type":"code","id":"spVhs0um0boM"},"outputs":[],"source":"!pip install pyppeteer\n!pip install beautifulsoup4\n!pip install nest_asyncio\n!pip install asyncio\n!pip install lxml"},{"cell_type":"markdown","metadata":{"colab_type":"text","id":"39tTDWFOPah3"},"outputs":[],"source":["# Importing"]},{"cell_type":"code","execution_count":31,"metadata":{},"outputs":[],"source":"# coding=utf-8\n\nfrom pyppeteer import launch\nimport asyncio\nimport nest_asyncio\nfrom bs4 import BeautifulSoup as bs\nimport re\nfrom dataclasses import dataclass\nimport time\nimport pandas as pd\nimport requests\nimport pysnooper\nimport os"},{"cell_type":"code","execution_count":2,"metadata":{},"outputs":[],"source":""},{"cell_type":"markdown","execution_count":null,"metadata":{},"outputs":[],"source":"# Data"},{"cell_type":"markdown","execution_count":null,"metadata":{},"outputs":[],"source":"## Data Set Up"},{"cell_type":"code","execution_count":3,"metadata":{},"outputs":[],"source":"nest_asyncio.apply()\n\n@dataclass\nclass Product:\n    product_index: int\n    product_type: str\n    product_name: str\n    prodect_brand: str\n    price: float\n    avg_rating: float\n    total_comment: int\n    seller: str\n    website: str\n\n@dataclass\nclass Customer:\n    product_index: int\n    username: str\n    user_rate: float\n    rate_date: str\n    buyer_comment: str\n\n\n        \nproduct_type_dict = {\n    \"平板電腦\": \"Tablet\",\n    \"手機\": \"Mobile Phone\",\n    \"手提電腦\": \"Laptop\"\n}\n\npd.set_option('display.max_columns', None)\npd.set_option('display.width', 500)\npd.set_option('display.max_colwidth', 50)\n\n\ncolumn_product = ['product_index', 'product_type', 'product_name', 'prodect_brand', 'price', 'avg_rating', 'total_comment', 'seller', 'website']\ncolumn_customer = ['product_index', 'username', 'user_rate', 'rate_date', 'buyer_comment']\n\nlist_pages = []\nlist_browsers = []"},{"cell_type":"markdown","execution_count":null,"metadata":{},"outputs":[],"source":"## Data storage"},{"cell_type":"code","execution_count":4,"metadata":{},"outputs":[],"source":"all_product = []\n\nall_customer = []\n\nitem_urls = {}"},{"cell_type":"markdown","metadata":{"colab_type":"text","id":"9C8K1jqCPqKV"},"outputs":[],"source":"## Websites that are needed to be crawling"},{"cell_type":"code","execution_count":5,"metadata":{},"outputs":[],"source":"all_urls = {\n        \"tablet\": \"https://search.hksuning.com/search/list?ci=503692\", # url_tablet\n        \"laptop\": \"https://search.hksuning.com/search/list?ci=503694\", # url_laptop\n        \"phone\": \"https://search.hksuning.com/search/list?ci=503505\" # url_phone\n}"},{"cell_type":"markdown","metadata":{"colab_type":"text","id":"37o8-YWxP0bP"},"outputs":[],"source":"# Return web page object of each category"},{"cell_type":"code","execution_count":6,"metadata":{},"outputs":[],"source":"async def get_item(categroy: str):\n    # browser = await launch()\n    print(\"Setting up broswer for web page...\")\n    \n    browser = await launch({\n            \"headless\": False,\n        })\n    page = await browser.newPage()\n    \n    await page.setViewport({'width': 1920, 'height': 1080})\n    await page.goto(categroy, {'timeout': 10000*30})\n    return page, browser"},{"cell_type":"markdown","metadata":{"colab_type":"text","id":"m7Ed6qjvQdfy"},"outputs":[],"source":["# Start crawling"]},{"cell_type":"markdown","metadata":{"colab_type":"text","id":"Yo3wEqHZghwb"},"outputs":[],"source":"## Get page of each item"},{"cell_type":"code","execution_count":7,"metadata":{},"outputs":[],"source":"def get_pages(num):\n\n    key = list(all_urls.items())[num][0]\n    url = list(all_urls.items())[num][1]\n\n    page, browser = asyncio.get_event_loop().run_until_complete(get_item(url))\n    page_num = asyncio.get_event_loop().run_until_complete(\n        get_page_num(page)\n    )\n\n    print(f\"There are total {page_num} pages about {key}\")\n\n    # list_pages.append(page)\n    list_browsers.append(browser)\n\n    return page, browser, page_num"},{"cell_type":"markdown","execution_count":null,"metadata":{},"outputs":[],"source":"## Return number of pages of one categroy"},{"cell_type":"code","execution_count":8,"metadata":{},"outputs":[],"source":"async def get_page_num(page) -> int:\n    content = bs(await page.content(), 'lxml')\n    page_num = re.findall(re.compile(r\"共\\d頁\"), content.prettify())[0][1]\n    return int(page_num)"},{"cell_type":"code","execution_count":8,"metadata":{},"outputs":[],"source":"u = list(all_urls.items())\nu[0][1]"},{"cell_type":"code","execution_count":7,"metadata":{},"outputs":[],"source":"page_tablet, browser_tablet = asyncio.get_event_loop().run_until_complete(get_item(u[0][1]))\n\npage_num_tablet = asyncio.get_event_loop().run_until_complete(\n        get_page_num(page_tablet)\n    )\nprint(f\"There are total {page_num_tablet} pages about tablet\")"},{"cell_type":"code","execution_count":25,"metadata":{},"outputs":[],"source":"page_laptop, browser_laptop = asyncio.get_event_loop().run_until_complete(get_item(u[1][1]))\n\npage_num_laptop = asyncio.get_event_loop().run_until_complete(\n        get_page_num(page_laptop)\n    )\nprint(f\"There are total {page_num_laptop} pages about laptop\")\n\n# asyncio.get_event_loop().run_until_complete(get_url(page_laptop))"},{"cell_type":"code","execution_count":38,"metadata":{},"outputs":[],"source":"page_phone, browser_phone = asyncio.get_event_loop().run_until_complete(get_item(u[2][1]))\n\npage_num_phone = asyncio.get_event_loop().run_until_complete(\n        get_page_num(page_phone)\n    )\nprint(f\"There are total {page_num_phone} pages about mobile phone\")\n\nasyncio.get_event_loop().run_until_complete(get_url(page_phone))\n# await browser_phone.close()"},{"cell_type":"markdown","metadata":{"colab_type":"text","id":"K0cSf5QeZ2oU"},"outputs":[],"source":["### Have next page button?"]},{"cell_type":"code","execution_count":9,"metadata":{},"outputs":[],"source":"async def have_button(page) -> bool:\n# regex\n    source = bs(await page.content(), 'lxml').prettify()\n    next_button_regex = re.compile(r'<a class=\"next\"[\\S*\\s*]*>\\s*<b>')\n\n    next_btn_src = re.findall(next_button_regex, source)[0]\n\n    if 'style=\"display: none;\"' in next_btn_src:\n        return False\n    else:\n        return True\n\n# asyncio.get_event_loop().run_until_complete(have_button(page_laptop))"},{"cell_type":"markdown","metadata":{},"outputs":[],"source":["### Last page"]},{"cell_type":"code","execution_count":10,"metadata":{},"outputs":[],"source":"async def click_last_page(page) ->bool:\n    last_btn_selector = \"#bottom_pager > div > a.prev\"\n    try:\n        await page.click(last_btn_selector)\n        return True\n    except :\n        return False\n        \n# asyncio.get_event_loop().run_until_complete(click_last_page(page_tablet))"},{"cell_type":"markdown","metadata":{"colab_type":"text","id":"6x1hzpQ6lZQ9"},"outputs":[],"source":["### Click next page button"]},{"cell_type":"code","execution_count":11,"metadata":{},"outputs":[],"source":"async def click_next_page(page) -> bool:\n    next_btn_selector = \"#bottom_pager > div > a.next\"\n    is_next = asyncio.get_event_loop().run_until_complete(have_button(page))\n\n    if is_next:\n        try:\n            await page.click(next_btn_selector)\n            return True\n        except:\n            return False\n    else:\n        # print(\"No next page!\")\n        return False"},{"cell_type":"markdown","execution_count":null,"metadata":{},"outputs":[],"source":"## Resolve Data"},{"cell_type":"code","execution_count":122,"metadata":{},"outputs":[],"source":"async def resolve_data(page, key):\n\n    print(f\"Getting product {key}...\")\n\n    source = bs(await page.content(), 'lxml')\n\n    time.sleep(2)\n\n    _product_index = key\n    \n    type_html = source.select('#pcFourth > div:nth-child(1) > div > ul > li:nth-child(5) > span > a')\n    _product_type = product_type_dict[type_html[0].get_text()]\n    \n    title = source.h1.get_text()\n    _product_name = title.replace(\"自營\", \"\").replace(\"香港倉\", \"\").strip()\n    \n    _product_brand = _product_name.split(\" \")[0]\n    \n    text_price = f\"{source.find('span', class_='integer').get_text()}.{source.find('span', class_='decimal').get_text()}\".strip()\n    _price = float(text_price)\n\n    tmp_seller = source.select('#pcFourth > div.wrapper.mt15 > div.procon-side > div.si-intro > div.si-intro-list > dl > dd')[0]\n    _seller = tmp_seller.get_text().replace(\"<dd>\", \"\").replace(\"</dd>\", \"\").strip()\n    \n    _website = item_urls.get(key)\n\n    # print(_seller)\n\n    # await page.evaluate(\"\"\"{window.scrollBy(0, document.body.scrollHeight);}\"\"\")\n\n    comment_regex = re.compile(r'<a>\\s*評價\\s*<span>\\s*(\\D*\\d*\\D*|\\S)\\s*</span>')\n    comment_str = re.findall(comment_regex, source.prettify())\n\n    _avg_rating = -1.0\n\n    _total_comment = 0\n\n    if comment_str[0] is not '':\n\n        # Click the comment tab\n        await page.click('#commentNum')\n\n        time.sleep(1)\n\n\n        while not await page.querySelector('#appraise > div.rv-wrap > div.rv-container.db > div.rv-rate.rv-bars') :\n            pass\n\n        _total_comment, _avg_rating = resolve_customer(key)\n    \n\n    print(f\"Got {_total_comment} comments of product {key}\")\n\n    one_product = [_product_index, _product_type, _product_name, _product_brand, _price, _avg_rating, _total_comment, _seller, _website]\n    all_product.append(one_product)\n"},{"cell_type":"code","execution_count":121,"metadata":{},"outputs":[],"source":"def resolve_customer(key) -> int:\n    print(f\"Getting comments of product {key}...\")\n\n    exist_comment = len(all_customer)\n\n    _product_index = key\n    \n    have_more_comment = True\n\n    p = 1\n    while have_more_comment:\n        time.sleep(1)\n        \n        r_url = f'https://product.hksuning.com/proxy/review/hk/ajax/review_lists/general-0000000{key}-0000000000-total-{p}-default-10-----reviewList.htm?callback=reviewList'\n\n        page_source = requests.get(r_url).text\n\n        user_regex = re.compile(r'\"nickName\":\"(\\S+)\",\"levelId\"')\n        date_regex = re.compile(r'\"publishTime\":\"(\\d+-\\d+-\\d+ \\d+:\\d+:\\d+)\",\"publishTimeStr\"')\n        comment_regex = re.compile(r'\"content\":\"(#?[\\S+，?]*\\s?\\S+#?)\",\"publishTime\"')\n        rate_regex = re.compile(r'\"qualityStar\":(\\d+),\"bestFlag\"')\n\n        all_username = re.findall(user_regex, page_source)\n        all_date = re.findall(date_regex, page_source)\n        all_comment = re.findall(comment_regex, page_source)\n        all_rate = re.findall(rate_regex, page_source)\n\n        num_user = len(all_username)\n        tmp_rate = 0\n\n        for n in range(num_user):\n            _username = all_username[n]\n            _rate_date = all_date[n]\n            _buyer_comment = all_comment[n]\n            _user_rate = int(all_rate[n])\n\n            tmp_rate += _user_rate\n\n            one_customer = [_product_index, _username, _user_rate, _rate_date, _buyer_comment]\n            all_customer.append(one_customer) \n\n        # print(f\"Got {key} comments page {p}\")\n\n        rtn_msg = re.findall(re.compile(r'\"returnMsg\":\"(\\w*)\",\"reCloudDrill\"'), page_source)[0]\n\n        if \"成功\" not in rtn_msg:\n            have_more_comment = False\n            # print(\"End\")\n            num_comments = len(all_customer) - exist_comment\n            rating = tmp_rate / num_comments\n            return num_comments, rating\n      \n        p += 1\n        # print(_rate_date)\n\n        time.sleep(1)\n \n"},{"cell_type":"code","execution_count":125,"metadata":{},"outputs":[{"name":"stdout","output_type":"stream","text":"Setting up broswer for web page...\n"}],"source":"# u = list(item_urls.items())[0]\n# print(u)\nuu = \"https://product.hksuning.com/0000000000/10674060101.html\"\npage_tmp, browser_tmp = asyncio.get_event_loop().run_until_complete(get_item(uu))"},{"cell_type":"code","execution_count":130,"metadata":{},"outputs":[],"source":"async def close_b():\n    # await page_tmp.close()\n    await browser_tmp.close()\n\nasyncio.get_event_loop().run_until_complete(close_b())"},{"cell_type":"code","execution_count":128,"metadata":{},"outputs":[{"name":"stdout","output_type":"stream","text":"Getting product 10674060101...\nGetting comments of product 10674060101...\nGot 505 comments of product 10674060101\n"}],"source":"asyncio.get_event_loop().run_until_complete(resolve_data(page_tmp, '10674060101'))\n# save_csv()"},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":""},{"cell_type":"markdown","execution_count":null,"metadata":{},"outputs":[],"source":"## Save Data"},{"cell_type":"code","execution_count":55,"metadata":{},"outputs":[],"source":"def save_csv():\n    df_product = pd.DataFrame(all_product, columns=column_product)\n    df_product.to_csv(\"Web Crawling/data/Suning/Products_Suning.csv\", sep=',', na_rep='N/A', encoding=\"utf_8_sig\")\n    print(df_product)\n\n    df_customer = pd.DataFrame(all_customer, columns=column_customer)\n    df_customer.to_csv(\"Web Crawling/data/Suning/Customers_Suning.csv\", sep=',', na_rep='N/A', encoding=\"utf_8_sig\")\n    print(df_customer)\n\n# save_csv()"},{"cell_type":"code","execution_count":129,"metadata":{},"outputs":[{"name":"stdout","output_type":"stream","text":"product_index  product_type                                       product_name prodect_brand    price  avg_rating  total_comment seller                                            website\n0     10964124069        Tablet  APPLE IPAD AIR 10.5 64GB WIFI GOLD MUUL2ZP/A 平板電腦         APPLE   3699.0         0.0            216   香港蘇寧  https://product.hksuning.com/0000000000/109641...\n1     10964145615        Tablet  APPLE IPAD MINI 2019 64GB WIFI SPACE GREY MUQW...         APPLE   2988.0         0.0            203   香港蘇寧  https://product.hksuning.com/0000000000/109641...\n2     10555865475        Tablet  Apple iPad Pro 12.9 1TB Wi-Fi Space Gray MTFR2...         Apple  12499.0         0.0              5   香港蘇寧  https://product.hksuning.com/0000000000/105558...\n3     11359867696        Tablet  Apple iPad 10.2 Wifi 32GB Space Gray MW742ZP/A...         Apple   2599.0        -1.0              0   香港蘇寧  https://product.hksuning.com/0000000000/113598...\n4     10964145617        Tablet  APPLE IPAD MINI 2019 64GB WIFI SILVER MUQX2ZP/...         APPLE   2988.0         0.0            194   香港蘇寧  https://product.hksuning.com/0000000000/109641...\n..            ...           ...                                                ...           ...      ...         ...            ...    ...                                                ...\n335   11356505293  Mobile Phone                    APPLE IPHONE 11 PRO 64GB 手機 太空灰         APPLE   8599.0        -1.0              0   香港蘇寧  https://product.hksuning.com/0000000000/113565...\n336   11039060815  Mobile Phone                   SAMSUNG GALAXY A70 手機 8+128GB 黑色       SAMSUNG   2798.0         0.0            326   香港蘇寧  https://product.hksuning.com/0000000000/110390...\n337   11039060816  Mobile Phone                   SAMSUNG GALAXY A70 手機 8+128GB 藍色       SAMSUNG   2798.0         0.0            247   香港蘇寧  https://product.hksuning.com/0000000000/110390...\n338   11356505297  Mobile Phone                     APPLE IPHONE 11 PRO 64GB 手機 金色         APPLE   8599.0        -1.0              0   香港蘇寧  https://product.hksuning.com/0000000000/113565...\n339   10674060101  Mobile Phone                             HUAWEI MATE 20 X 手機 藍色        HUAWEI   4988.0         0.0            505   香港蘇寧  https://product.hksuning.com/0000000000/106740...\n\n[340 rows x 9 columns]\n      product_index username  user_rate            rate_date   buyer_comment\n0       10964124069    6***8          5  2019-06-20 17:25:27          發貨快,正品\n1       10964124069    小***姐          5  2019-09-29 21:40:40  和之前iPadpro感覺一樣\n2       10964124069    9***6          5  2019-09-21 19:54:59             非常快\n3       10964124069    7***1          5  2019-10-15 19:06:08     买家没有填写评价内容！\n4       10964124069    6***8          5  2019-10-14 12:42:37     买家没有填写评价内容！\n...             ...      ...        ...                  ...             ...\n49157   10674060101    6***6          5  2019-04-12 16:40:23     买家没有填写评价内容！\n49158   10674060101    7***2          5  2019-04-12 11:10:37     买家没有填写评价内容！\n49159   10674060101    7***8          5  2019-04-12 10:55:46     买家没有填写评价内容！\n49160   10674060101    6***9          5  2019-04-12 06:16:02     买家没有填写评价内容！\n49161   10674060101    7***7          5  2019-04-11 15:50:35     买家没有填写评价内容！\n\n[49162 rows x 5 columns]\n"}],"source":"save_csv()"},{"cell_type":"markdown","metadata":{},"outputs":[],"source":"## URLs"},{"cell_type":"markdown","metadata":{"colab_type":"text","id":"2_pHSJaNo6YF"},"outputs":[],"source":"### Get all item url"},{"cell_type":"code","execution_count":15,"metadata":{},"outputs":[],"source":"async def get_url(page):   \n\n    time.sleep(2)\n    source = bs(await page.content(), 'lxml').prettify()\n\n    item_id = re.findall(\n            re.compile(r'(?<=//product.hksuning.com/0000000000/)(\\d*).html'),\n            source\n        )\n    item_id = list(dict.fromkeys(item_id))\n    tmp_dict = {}\n    \n    for i in item_id:\n        url_patten = f\"https://product.hksuning.com/0000000000/{i}.html\"\n        tmp_dict[i] = url_patten\n        item_urls.update(tmp_dict)\n        \n    while asyncio.get_event_loop().run_until_complete(have_button(page)):      \n        # Click next page button\n        asyncio.get_event_loop().run_until_complete(click_next_page(page))\n\n        # print(\"next\")\n        # await page.screenshot({'path': 'example.png'})\n        time.sleep(2)\n        \n        # Get URLs\n        asyncio.get_event_loop().run_until_complete(get_url(page))\n\n\n# asyncio.get_event_loop().run_until_complete(get_url(page_tablet))\n"},{"cell_type":"markdown","metadata":{},"outputs":[],"source":["### URLs Traversal"]},{"cell_type":"code","execution_count":119,"metadata":{},"outputs":[],"source":"def delete_item(required: str):\n    for p in all_product:\n        if required in p:\n            all_product.remove(p)\n\n    for c in all_customer:\n        if required in c:\n            all_customer.remove(c)\n"},{"cell_type":"code","execution_count":127,"metadata":{},"outputs":[],"source":"delete_item('10674060101')"},{"cell_type":"code","execution_count":80,"metadata":{},"outputs":[],"source":"async def interrupt_traversal():\n    start_from = 282\n    current_index = start_from\n    while current_index < len(item_urls) - 1:\n        item = list(item_urls.items())[current_index]\n        key = item[0]\n        url = item[1]\n\n        page, browser = asyncio.get_event_loop().run_until_complete(\n                get_item(url)\n            )\n        asyncio.get_event_loop().run_until_complete(resolve_data(page, key))\n\n        time.sleep(1)\n\n        await browser.close()\n\n        time.sleep(3)\n\n        current_index += 1\n"},{"cell_type":"code","execution_count":123,"metadata":{},"outputs":[{"name":"stdout","output_type":"stream","text":"er for web page...\nGetting product 11136280253...\nGetting comments of product 11136280253...\nGot 43 comments of product 11136280253\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10584849209...\nGot 0 comments of product 10584849209\nSetting up broswer for web page...\nGetting product 10944549906...\nGetting comments of product 10944549906...\nGot 44 comments of product 10944549906\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11136280258...\nGetting comments of product 11136280258...\nGot 37 comments of product 11136280258\nSetting up broswer for web page...\nGetting product 10532526617...\nGetting comments of product 10532526617...\nGot 444 comments of product 10532526617\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10686527830...\nGetting comments of product 10686527830...\nGot 14 comments of product 10686527830\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10584849613...\nGot 0 comments of product 10584849613\nSetting up broswer for web page...\nGetting product 11197208554...\nGetting comments of product 11197208554...\nGot 52 comments of product 11197208554\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10584534153...\nGetting comments of product 10584534153...\nGot 11 comments of product 10584534153\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11356505269...\nGot 0 comments of product 11356505269\nSetting up broswer for web page...\nGetting product 10584849617...\nGot 0 comments of product 10584849617\nSetting up broswer for web page...\nGetting product 11039060812...\nGot 0 comments of product 11039060812\nSetting up broswer for web page...\nGetting product 11191799773...\nGetting comments of product 11191799773...\nGot 271 comments of product 11191799773\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10584849492...\nGetting comments of product 10584849492...\nGot 507 comments of product 10584849492\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11039060813...\nGetting comments of product 11039060813...\nGot 306 comments of product 11039060813\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10584849493...\nGetting comments of product 10584849493...\nGot 502 comments of product 10584849493\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11039060814...\nGetting comments of product 11039060814...\nGot 349 comments of product 11039060814\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11193559892...\nGetting comments of product 11193559892...\nGot 34 comments of product 11193559892\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11356505294...\nGot 0 comments of product 11356505294\nSetting up broswer for web page...\nGetting product 10584849494...\nGetting comments of product 10584849494...\nGot 374 comments of product 10584849494\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11191646476...\nGetting comments of product 11191646476...\nGot 219 comments of product 11191646476\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11314864607...\nGetting comments of product 11314864607...\nGot 92 comments of product 11314864607\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11356505298...\nGot 0 comments of product 11356505298\nSetting up broswer for web page...\nGetting product 11356500073...\nGot 0 comments of product 11356500073\nSetting up broswer for web page...\nGetting product 11356500075...\nGot 0 comments of product 11356500075\nSetting up broswer for web page...\nGetting product 10674060101...\nGot 0 comments of product 10674060101\nSetting up broswer for web page...\nGetting product 656160880...\nGetting comments of product 656160880...\nGot 70 comments of product 656160880\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11356505334...\nGot 0 comments of product 11356505334\nSetting up broswer for web page...\nGetting product 11356505335...\nGetting comments of product 11356505335...\nGot 2 comments of product 11356505335\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11356505274...\nGot 0 comments of product 11356505274\nSetting up broswer for web page...\nGetting product 11008663596...\nGetting comments of product 11008663596...\nGot 284 comments of product 11008663596\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11356505277...\nGot 0 comments of product 11356505277\nSetting up broswer for web page...\nGetting product 11356505278...\nGetting comments of product 11356505278...\nGot 1 comments of product 11356505278\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11026147265...\nGetting comments of product 11026147265...\nGot 129 comments of product 11026147265\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11020212649...\nGetting comments of product 11020212649...\nGot 501 comments of product 11020212649\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11356505287...\nGot 0 comments of product 11356505287\nSetting up broswer for web page...\nGetting product 11356505288...\nGot 0 comments of product 11356505288\nSetting up broswer for web page...\nGetting product 11356505289...\nGot 0 comments of product 11356505289\nSetting up broswer for web page...\nGetting product 170114328...\nGetting comments of product 170114328...\nGot 250 comments of product 170114328\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11020212650...\nGetting comments of product 11020212650...\nGot 208 comments of product 11020212650\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11356500069...\nGot 0 comments of product 11356500069\nSetting up broswer for web page...\nGetting product 150843468...\nGetting comments of product 150843468...\nGot 51 comments of product 150843468\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11356505266...\nGot 0 comments of product 11356505266\nSetting up broswer for web page...\nGetting product 10578454629...\nGetting comments of product 10578454629...\nGot 2 comments of product 10578454629\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10584849529...\nGetting comments of product 10584849529...\nGot 500 comments of product 10584849529\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10584849614...\nGetting comments of product 10584849614...\nGot 2 comments of product 10584849614\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11362693468...\nGot 0 comments of product 11362693468\nSetting up broswer for web page...\nGetting product 11356505293...\nGot 0 comments of product 11356505293\nSetting up broswer for web page...\nGetting product 11039060815...\nGetting comments of product 11039060815...\nGot 326 comments of product 11039060815\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11039060816...\nGetting comments of product 11039060816...\nGot 247 comments of product 11039060816\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11356505297...\nGot 0 comments of product 11356505297\n"}],"source":"asyncio.get_event_loop().run_until_complete(interrupt_traversal())"},{"cell_type":"code","execution_count":16,"metadata":{},"outputs":[],"source":"async def traversal():\n    \n    for key, value in item_urls.items():\n        page, browser = asyncio.get_event_loop().run_until_complete(get_item(value))        \n        asyncio.get_event_loop().run_until_complete(resolve_data(page, key))\n        \n        time.sleep(1)\n\n        await browser.close()\n\n        time.sleep(3)\n"},{"cell_type":"code","execution_count":58,"metadata":{},"outputs":[{"name":"stdout","output_type":"stream","text":"t 10586383781...\nGot 424 comments of product 10586383781\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11362846166...\nGot 0 comments of product 11362846166\nSetting up broswer for web page...\nGetting product 10584849457...\nGetting comments of product 10584849457...\nGot 510 comments of product 10584849457\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10586383782...\nGetting comments of product 10586383782...\nGot 379 comments of product 10586383782\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10676500905...\nGetting comments of product 10676500905...\nGot 311 comments of product 10676500905\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10586383783...\nGetting comments of product 10586383783...\nGot 271 comments of product 10586383783\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10584849312...\nGot 0 comments of product 10584849312\nSetting up broswer for web page...\nGetting product 11356505282...\nGot 0 comments of product 11356505282\nSetting up broswer for web page...\nGetting product 10584849251...\nGetting comments of product 10584849251...\nGot 49 comments of product 10584849251\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10612565854...\nGetting comments of product 10612565854...\nGot 231 comments of product 10612565854\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11356505283...\nGot 0 comments of product 11356505283\nSetting up broswer for web page...\nGetting product 10584849315...\nGetting comments of product 10584849315...\nGot 504 comments of product 10584849315\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11191799765...\nGetting comments of product 11191799765...\nGot 335 comments of product 11191799765\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11356505284...\nGot 0 comments of product 11356505284\nSetting up broswer for web page...\nGetting product 10584849318...\nGetting comments of product 10584849318...\nGot 506 comments of product 10584849318\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11308814854...\nGot 0 comments of product 11308814854\nSetting up broswer for web page...\nGetting product 11026147271...\nGetting comments of product 11026147271...\nGot 218 comments of product 11026147271\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10532528362...\nGetting comments of product 10532528362...\nGot 412 comments of product 10532528362\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10584852176...\nGot 0 comments of product 10584852176\nSetting up broswer for web page...\nGetting product 10569646283...\nGetting comments of product 10569646283...\nGot 7 comments of product 10569646283\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10572433360...\nGetting comments of product 10572433360...\nGot 157 comments of product 10572433360\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10584852177...\nGot 0 comments of product 10584852177\nSetting up broswer for web page...\nGetting product 10620163685...\nGetting comments of product 10620163685...\nGot 373 comments of product 10620163685\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10719285049...\nGetting comments of product 10719285049...\nGot 45 comments of product 10719285049\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11314864622...\nGetting comments of product 11314864622...\nGot 39 comments of product 11314864622\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11026147274...\nGetting comments of product 11026147274...\nGot 419 comments of product 11026147274\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11143482027...\nGot 0 comments of product 11143482027\nSetting up broswer for web page...\nGetting product 11193559889...\nGetting comments of product 11193559889...\nGot 27 comments of product 11193559889\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10583408744...\nGetting comments of product 10583408744...\nGot 420 comments of product 10583408744\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10584849281...\nGetting comments of product 10584849281...\nGot 83 comments of product 10584849281\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10584849660...\nGot 0 comments of product 10584849660\nSetting up broswer for web page...\nGetting product 11020212651...\nGetting comments of product 11020212651...\nGot 502 comments of product 11020212651\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11026147276...\nGot 0 comments of product 11026147276\nSetting up broswer for web page...\nGetting product 10584849430...\nGetting comments of product 10584849430...\nGot 489 comments of product 10584849430\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11020212652...\nGetting comments of product 11020212652...\nGot 500 comments of product 11020212652\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11020212653...\nGot 0 comments of product 11020212653\nSetting up broswer for web page...\nGetting product 10584849663...\nGot 0 comments of product 10584849663\nSetting up broswer for web page...\nGetting product 11020212654...\nGot 0 comments of product 11020212654\nSetting up broswer for web page...\nGetting product 10584849433...\nGot 0 comments of product 10584849433\nSetting up broswer for web page...\nGetting product 10676511066...\nGetting comments of product 10676511066...\nGot 334 comments of product 10676511066\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10859217499...\nGetting comments of product 10859217499...\nGot 5 comments of product 10859217499\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 11356500068...\nGot 0 comments of product 11356500068\nSetting up broswer for web page...\nGetting product 10524360588...\nGetting comments of product 10524360588...\nGot 239 comments of product 10524360588\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10584849373...\nGetting comments of product 10584849373...\nGot 504 comments of product 10584849373\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10584849436...\nGetting comments of product 10584849436...\nGot 502 comments of product 10584849436\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10859217502...\nGetting comments of product 10859217502...\nGot 8 comments of product 10859217502\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10584849206...\nGetting comments of product 10584849206...\n"},{"ename":"IndexError","evalue":"list index out of range","output_type":"error","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mIndexError\u001b[0m                                Traceback (most recent call last)","\u001b[1;32m<ipython-input-58-79ee10d6097a>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0masyncio\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget_event_loop\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrun_until_complete\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtraversal\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\u001b[0m in \u001b[0;36mrun_until_complete\u001b[1;34m(self, future)\u001b[0m\n\u001b[0;32m    577\u001b[0m             \u001b[1;32mraise\u001b[0m \u001b[0mRuntimeError\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'Event loop stopped before Future completed.'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    578\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 579\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0mfuture\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mresult\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    580\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    581\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0mstop\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\asyncio\\futures.py\u001b[0m in \u001b[0;36mresult\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    176\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__log_traceback\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;32mFalse\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    177\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_exception\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 178\u001b[1;33m             \u001b[1;32mraise\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_exception\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    179\u001b[0m         \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_result\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    180\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\asyncio\\tasks.py\u001b[0m in \u001b[0;36m__step\u001b[1;34m(***failed resolving arguments***)\u001b[0m\n\u001b[0;32m    247\u001b[0m                 \u001b[1;31m# We use the `send` method directly, because coroutines\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    248\u001b[0m                 \u001b[1;31m# don't have `__iter__` and `__next__` methods.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 249\u001b[1;33m                 \u001b[0mresult\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mcoro\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msend\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;32mNone\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    250\u001b[0m             \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    251\u001b[0m                 \u001b[0mresult\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mcoro\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mthrow\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mexc\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;32m<ipython-input-16-d1aa6456250a>\u001b[0m in \u001b[0;36mtraversal\u001b[1;34m()\u001b[0m\n\u001b[0;32m      3\u001b[0m     \u001b[1;32mfor\u001b[0m \u001b[0mkey\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mvalue\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mitem_urls\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mitems\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      4\u001b[0m         \u001b[0mpage\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mbrowser\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0masyncio\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget_event_loop\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrun_until_complete\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mget_item\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mvalue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 5\u001b[1;33m         \u001b[0masyncio\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget_event_loop\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrun_until_complete\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mresolve_data\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mpage\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mkey\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      6\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      7\u001b[0m         \u001b[0mtime\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msleep\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\u001b[0m in \u001b[0;36mrun_until_complete\u001b[1;34m(self, future)\u001b[0m\n\u001b[0;32m    577\u001b[0m             \u001b[1;32mraise\u001b[0m \u001b[0mRuntimeError\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'Event loop stopped before Future completed.'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    578\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 579\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0mfuture\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mresult\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    580\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    581\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0mstop\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\asyncio\\futures.py\u001b[0m in \u001b[0;36mresult\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    176\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__log_traceback\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;32mFalse\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    177\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_exception\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 178\u001b[1;33m             \u001b[1;32mraise\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_exception\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    179\u001b[0m         \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_result\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    180\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\asyncio\\tasks.py\u001b[0m in \u001b[0;36m__step\u001b[1;34m(***failed resolving arguments***)\u001b[0m\n\u001b[0;32m    247\u001b[0m                 \u001b[1;31m# We use the `send` method directly, because coroutines\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    248\u001b[0m                 \u001b[1;31m# don't have `__iter__` and `__next__` methods.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 249\u001b[1;33m                 \u001b[0mresult\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mcoro\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msend\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;32mNone\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    250\u001b[0m             \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    251\u001b[0m                 \u001b[0mresult\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mcoro\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mthrow\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mexc\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;32m<ipython-input-12-a05b6921c5a6>\u001b[0m in \u001b[0;36mresolve_data\u001b[1;34m(page, key)\u001b[0m\n\u001b[0;32m     47\u001b[0m             \u001b[1;32mpass\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     48\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 49\u001b[1;33m         \u001b[0m_total_comment\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0m_avg_rating\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mresolve_customer\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mkey\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     50\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     51\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;32m<ipython-input-13-c498624b733a>\u001b[0m in \u001b[0;36mresolve_customer\u001b[1;34m(key)\u001b[0m\n\u001b[0;32m     32\u001b[0m             \u001b[0m_username\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mall_username\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mn\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     33\u001b[0m             \u001b[0m_rate_date\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mall_date\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mn\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 34\u001b[1;33m             \u001b[0m_buyer_comment\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mall_comment\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mn\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     35\u001b[0m             \u001b[0m_user_rate\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mall_rate\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mn\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     36\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;31mIndexError\u001b[0m: list index out of range"]}],"source":"asyncio.get_event_loop().run_until_complete(traversal())"},{"cell_type":"markdown","metadata":{"colab":{},"colab_type":"code","id":"noUdljtbgoEO"},"outputs":[],"source":["## Main"]},{"cell_type":"code","execution_count":17,"metadata":{},"outputs":[],"source":"# @pysnooper.snoop()\nasync def main():\n    process_num = len(all_urls)\n\n    for index in range(process_num):\n        page, browser, page_num = get_pages(index)\n        asyncio.get_event_loop().run_until_complete(get_url(page))\n        \n        time.sleep(0.5)\n\n        await browser.close()\n        \n        print(f\"Got total {len(item_urls)} URLs\")\n\n        time.sleep(2)\n    \n    asyncio.get_event_loop().run_until_complete(traversal())\n\n    save_csv()\n"},{"cell_type":"code","execution_count":19,"metadata":{},"outputs":[{"name":"stdout","output_type":"stream","text":"ol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10964145765...\nGetting comments of product 10964145765...\nGot 35 comments of product 10964145765\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10964145620...\nGetting comments of product 10964145620...\nGot 312 comments of product 10964145620\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10964145627...\nGetting comments of product 10964145627...\nGot 95 comments of product 10964145627\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10964145656...\nGetting comments of product 10964145656...\nGot 129 comments of product 10964145656\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10717774549...\nGetting comments of product 10717774549...\nGot 18 comments of product 10717774549\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10394995121...\nGetting comments of product 10394995121...\nGot 66 comments of product 10394995121\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10964145632...\nGetting comments of product 10964145632...\nGot 82 comments of product 10964145632\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10555863478...\nGetting comments of product 10555863478...\nGot 24 comments of product 10555863478\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10555862151...\nGetting comments of product 10555862151...\nGot 10 comments of product 10555862151\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10555566560...\nGetting comments of product 10555566560...\nGot 13 comments of product 10555566560\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10964145699...\nGetting comments of product 10964145699...\nGot 73 comments of product 10964145699\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10555846917...\nGetting comments of product 10555846917...\nGot 45 comments of product 10555846917\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10555868338...\nGetting comments of product 10555868338...\nGot 60 comments of product 10555868338\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10555805676...\nGetting comments of product 10555805676...\nGot 41 comments of product 10555805676\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10555866892...\nGetting comments of product 10555866892...\nGot 120 comments of product 10555866892\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10964124185...\nGetting comments of product 10964124185...\nGot 111 comments of product 10964124185\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10964124018...\nGetting comments of product 10964124018...\nGot 285 comments of product 10964124018\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10580223964...\nGetting comments of product 10580223964...\nGot 186 comments of product 10580223964\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10964124188...\nGetting comments of product 10964124188...\nGot 23 comments of product 10964124188\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 615437999...\nGetting comments of product 615437999...\nGot 58 comments of product 615437999\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10555845879...\nGetting comments of product 10555845879...\nGot 25 comments of product 10555845879\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10580223969...\nGetting comments of product 10580223969...\nGot 436 comments of product 10580223969\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10580992866...\nGetting comments of product 10580992866...\nGot 14 comments of product 10580992866\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10555867679...\nGetting comments of product 10555867679...\nGot 28 comments of product 10555867679\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10818305893...\nGetting comments of product 10818305893...\nGot 324 comments of product 10818305893\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10964145679...\nGetting comments of product 10964145679...\nGot 86 comments of product 10964145679\nSetting up broswer for web page...\nGetting product 10576193971...\nGetting comments of product 10576193971...\nGot 375 comments of product 10576193971\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10964124138...\nGetting comments of product 10964124138...\nGot 117 comments of product 10964124138\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10964145768...\nGot 0 comments of product 10964145768\nSetting up broswer for web page...\nGetting product 10555867477...\nGetting comments of product 10555867477...\nGot 33 comments of product 10555867477\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10964145562...\nGetting comments of product 10964145562...\nGot 40 comments of product 10964145562\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10555566928...\nGetting comments of product 10555566928...\nGot 29 comments of product 10555566928\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10395357178...\nGot 0 comments of product 10395357178\nSetting up broswer for web page...\nGetting product 10395189998...\nGetting comments of product 10395189998...\nGot 481 comments of product 10395189998\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10395360561...\nGetting comments of product 10395360561...\nGot 199 comments of product 10395360561\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Runtime.releaseObject: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Runtime.releaseObject: Target closed.\nFuture exception was never retrieved\nfuture: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>\npyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.\nSetting up broswer for web page...\nGetting product 10580992840...\n"},{"ename":"IndexError","evalue":"list index out of range","output_type":"error","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mIndexError\u001b[0m                                Traceback (most recent call last)","\u001b[1;32m<ipython-input-19-5776d10d15a1>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0masyncio\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget_event_loop\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrun_until_complete\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmain\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\u001b[0m in \u001b[0;36mrun_until_complete\u001b[1;34m(self, future)\u001b[0m\n\u001b[0;32m    577\u001b[0m             \u001b[1;32mraise\u001b[0m \u001b[0mRuntimeError\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'Event loop stopped before Future completed.'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    578\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 579\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0mfuture\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mresult\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    580\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    581\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0mstop\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\asyncio\\futures.py\u001b[0m in \u001b[0;36mresult\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    176\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__log_traceback\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;32mFalse\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    177\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_exception\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 178\u001b[1;33m             \u001b[1;32mraise\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_exception\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    179\u001b[0m         \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_result\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    180\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\asyncio\\tasks.py\u001b[0m in \u001b[0;36m__step\u001b[1;34m(***failed resolving arguments***)\u001b[0m\n\u001b[0;32m    247\u001b[0m                 \u001b[1;31m# We use the `send` method directly, because coroutines\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    248\u001b[0m                 \u001b[1;31m# don't have `__iter__` and `__next__` methods.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 249\u001b[1;33m                 \u001b[0mresult\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mcoro\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msend\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;32mNone\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    250\u001b[0m             \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    251\u001b[0m                 \u001b[0mresult\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mcoro\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mthrow\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mexc\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;32m<ipython-input-17-5445c0ab5c0f>\u001b[0m in \u001b[0;36mmain\u001b[1;34m()\u001b[0m\n\u001b[0;32m     15\u001b[0m         \u001b[0mtime\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msleep\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;36m2\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     16\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 17\u001b[1;33m     \u001b[0masyncio\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget_event_loop\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrun_until_complete\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtraversal\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     18\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     19\u001b[0m     \u001b[0msave_csv\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\u001b[0m in \u001b[0;36mrun_until_complete\u001b[1;34m(self, future)\u001b[0m\n\u001b[0;32m    577\u001b[0m             \u001b[1;32mraise\u001b[0m \u001b[0mRuntimeError\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'Event loop stopped before Future completed.'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    578\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 579\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0mfuture\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mresult\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    580\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    581\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0mstop\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\asyncio\\futures.py\u001b[0m in \u001b[0;36mresult\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    176\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__log_traceback\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;32mFalse\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    177\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_exception\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 178\u001b[1;33m             \u001b[1;32mraise\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_exception\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    179\u001b[0m         \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_result\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    180\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\asyncio\\tasks.py\u001b[0m in \u001b[0;36m__step\u001b[1;34m(***failed resolving arguments***)\u001b[0m\n\u001b[0;32m    247\u001b[0m                 \u001b[1;31m# We use the `send` method directly, because coroutines\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    248\u001b[0m                 \u001b[1;31m# don't have `__iter__` and `__next__` methods.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 249\u001b[1;33m                 \u001b[0mresult\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mcoro\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msend\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;32mNone\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    250\u001b[0m             \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    251\u001b[0m                 \u001b[0mresult\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mcoro\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mthrow\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mexc\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;32m<ipython-input-16-d1aa6456250a>\u001b[0m in \u001b[0;36mtraversal\u001b[1;34m()\u001b[0m\n\u001b[0;32m      3\u001b[0m     \u001b[1;32mfor\u001b[0m \u001b[0mkey\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mvalue\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mitem_urls\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mitems\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      4\u001b[0m         \u001b[0mpage\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mbrowser\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0masyncio\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget_event_loop\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrun_until_complete\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mget_item\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mvalue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 5\u001b[1;33m         \u001b[0masyncio\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget_event_loop\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrun_until_complete\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mresolve_data\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mpage\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mkey\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      6\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      7\u001b[0m         \u001b[0mtime\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msleep\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\u001b[0m in \u001b[0;36mrun_until_complete\u001b[1;34m(self, future)\u001b[0m\n\u001b[0;32m    577\u001b[0m             \u001b[1;32mraise\u001b[0m \u001b[0mRuntimeError\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'Event loop stopped before Future completed.'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    578\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 579\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0mfuture\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mresult\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    580\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    581\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0mstop\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\asyncio\\futures.py\u001b[0m in \u001b[0;36mresult\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    176\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__log_traceback\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;32mFalse\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    177\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_exception\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 178\u001b[1;33m             \u001b[1;32mraise\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_exception\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    179\u001b[0m         \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_result\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    180\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\asyncio\\tasks.py\u001b[0m in \u001b[0;36m__step\u001b[1;34m(***failed resolving arguments***)\u001b[0m\n\u001b[0;32m    247\u001b[0m                 \u001b[1;31m# We use the `send` method directly, because coroutines\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    248\u001b[0m                 \u001b[1;31m# don't have `__iter__` and `__next__` methods.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 249\u001b[1;33m                 \u001b[0mresult\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mcoro\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msend\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;32mNone\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    250\u001b[0m             \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    251\u001b[0m                 \u001b[0mresult\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mcoro\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mthrow\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mexc\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;32m<ipython-input-12-a05b6921c5a6>\u001b[0m in \u001b[0;36mresolve_data\u001b[1;34m(page, key)\u001b[0m\n\u001b[0;32m     10\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     11\u001b[0m     \u001b[0mtype_html\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0msource\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mselect\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'#pcFourth > div:nth-child(1) > div > ul > li:nth-child(5) > span > a'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 12\u001b[1;33m     \u001b[0m_product_type\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mproduct_type_dict\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mtype_html\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget_text\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     13\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     14\u001b[0m     \u001b[0mtitle\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0msource\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mh1\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget_text\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;31mIndexError\u001b[0m: list index out of range"]}],"source":"asyncio.get_event_loop().run_until_complete(main())"},{"cell_type":"code","execution_count":57,"metadata":{},"outputs":[],"source":"all_product.clear()\nall_customer.clear()"},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":""}],"nbformat":4,"nbformat_minor":2,"metadata":{"language_info":{"name":"python","codemirror_mode":{"name":"ipython","version":3}},"orig_nbformat":2,"file_extension":".py","mimetype":"text/x-python","name":"python","npconvert_exporter":"python","pygments_lexer":"ipython3","version":3}}